### ISSUE TITLE
Error while running the example

### ISSUE THREAD

**Issue by ThomasAn73** [atreadw1492/yahoo_fin#1]
Running the example in this repo gives the following error:

File "C:\Program Files\Python37\lib\site-packages\yahoo_fin\stock_info.py", line 82, in get_data
    result = result.sort_values("date")
File "C:\Program Files\Python37\lib\site-packages\pandas\core\frame.py", line 4719, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
File "C:\Program Files\Python37\lib\site-packages\pandas\core\generic.py", line 1702, in _get_label_or_level_values
    self._check_label_or_level_ambiguity(key, axis=axis)
File "C:\Program Files\Python37\lib\site-packages\pandas\core\generic.py", line 1656, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'date' is both an index level and a column label, which is ambiguous.

**Comment by mbzand** [comment]
I have the exact same problem. I tried updating yahoo_fin, but it didn't help. I hope there will be a solution soon.

**Comment by etcart** [comment]
also have this issue, any updates?

**Comment by etcart** [comment]
you can fix this by goign to line 339 in stock_info.py and replacing the df.close[-1] with a df.close[0]
and then go to the line that's throwing the error (line 82) and delete it.
no guarantee that this will always work, but it seems to, the array comes in sorted from most recent to least, and all the sort does is invert it.  so instead we can just read the first element

**Comment by ThermoDev** [comment]
On stock_info.py in line 81, just add the following lines directly after
```
result.index.name = None
result = result.rename_axis(None)
```
This will allow you to be able to still use the `sort_values()` function on lines 82.

**Comment by atreadw1492** [comment]
This should be resolved in the most recent version of yahoo_fin, which is now available.  You just need to reinstall it.
