### ISSUE TITLE
Possible typo on website

### ISSUE THREAD

**Issue by alik604** [atreadw1492/yahoo_fin#12]
Possible typo your website: 
Page: http://theautomatic.net/2019/04/17/how-to-get-options-data-with-python/
Heading: How to get options data for each expiration date

```python
nflx_dates= options.get_expiration_dates("nflx")
info = {}
for date in nflx_dates:
    info[date] = options.get_options_chain("nflx")
```

To my understanding should be the following, since `options.get_options_chain("nflx")` has not idea which "date" you want 

``` python 
nflx_dates= options.get_expiration_dates("nflx")
info = {}
for date in nflx_dates:
    info[date] =options.get_options_data("nflx", expiry=date)
```

I haven't used your library, perhaps I'm mistaken

**Comment by atreadw1492** [comment]
Thanks for noticing this.  I have corrected the typo.
