### ISSUE TITLE
Obsolete Requirements

### ISSUE THREAD

**Issue by apoorva-sriv** [atreadw1492/yahoo_fin#17]
The Requirements section in http://theautomatic.net/yahoo_fin-documentation/ should not have `ftplib`, `io`, and `json` since they are part of Python already. Removing them would help people who run `pip install -r requirements.txt`.

**Comment by atreadw1492** [comment]
yahoo_fin has been updated to automatically install any dependencies, so this shouldn't be an issue going forward.
