### ISSUE TITLE
Data obtained from get_options_chain are turned into object dtype

### ISSUE THREAD

**Issue by sine-w** [atreadw1492/yahoo_fin#19]
Hi,
First of all, thanks for this wonderful library.

I try to obtain the call put info via get_options_chain
and the ticker I used was ^NDX.

However I found that the data dtype for Open interest, pct change and volume are all regarded as type object , i.e. string.

I have try to convert it to numeric by 
call_df['Open Interest'] = pd.to_numeric(call_df['Open Interest'], errors='coerce')
    put_df['Open Interest'] = pd.to_numeric(put_df['Open Interest'], errors='coerce')

and it seemed failed.

if it is possible that the library can first do the data type check and do necessary data type convert first?
Thanks.

**Comment by atreadw1492** [comment]
Thanks for using yahoo_fin.  The next version of the package will include an option to automatically convert these fields to numeric.
