### ISSUE TITLE
exception when a calls/puts table is empty

### ISSUE THREAD

**Issue by birdchan** [atreadw1492/yahoo_fin#20]
options.get_options_chain('AVD', 'May 21, 2021') gives this error. 

  File "/Users/birdchan/my_git/docker-airflow/venv/lib/python3.7/site-packages/yahoo_fin/options.py", line 36, in get_options_chain
    puts = tables[1].copy()

https://finance.yahoo.com/quote/AVD/options?p=AVD&date=1621555200

Perhaps just return an empty dataframe.

**Comment by atreadw1492** [comment]
Hi @birdchan - this will be fixed in version 0.8.7.
