### ISSUE TITLE
Stale Data after multiple requests

### ISSUE THREAD

**Issue by wellerk1** [atreadw1492/yahoo_fin#21]
When looping through a large number of symbols to retrieve options data, the data returned is out of date after ~300 requests to options.get_options_chain(ticker)

[opts_py.txt](https://github.com/atreadw1492/yahoo_fin/files/5433983/opts_py.txt)

The last trade date no longer shows recent activity and the prices don't match.

This may be yahoo blocking mining attempts.

**Comment by atreadw1492** [comment]
Could be a throttling issue, but difficult to say for sure.
