### ISSUE TITLE
fix str strip for float conversion

### ISSUE THREAD

**Issue by gilbh** [atreadw1492/yahoo_fin#22]
Hi,

This is a rare scenario, but just happened today: the stock GRPEF has a change rate of "+249,900.00%" in daily gainers. This throws an `ValueError` exception in `stock_info(491)` when converting `str` to `float` because of the comma sign. Please change the line from:
`    df["% Change"] = df["% Change"].map(lambda x: float(x.strip("%+")))`
to
`    df["% Change"] = df["% Change"].map(lambda x: float(x.strip("%+").replace(",", "")))`

(Apologies for not forking etc., I am still new to GitHub).

Let me know if the above makes sense.

Best,
Gil

**Comment by atreadw1492** [comment]
Thanks for pointing out this issue.  Fixed this in the GitHub version.  I'll push this to PyPI in the next release.
