### ISSUE TITLE
get_data(ticker) return dataframe with empty data rows

### ISSUE THREAD

**Issue by sine-w** [atreadw1492/yahoo_fin#26]
Hi,
The historical data function return a pandas dataframe containing strange empty cells

I do the following
ticker = '^HSI'
yf_request = get_data(ticker)
and save dataframe as csv

In the csv, I found that some rows have only dates but all other cells are empty
for example, 21/10/2016 and 23/8/2017

**Comment by atreadw1492** [comment]
I did some research into this, and it looks like there's a legitimate reason why the data is missing.  For example, on 23/8/2017, the market was closed in Hong Kong that day due to a typhoon warning (see this: https://www.hkex.com.hk/news/market-communications/2017/1708232news?sc_lang=en).
