### ISSUE TITLE
get_quote_table does not work for CL=F

### ISSUE THREAD

**Issue by duivesteyn** [atreadw1492/yahoo_fin#27]
Has error on ticker "CL=F"
File "/usr/local/lib/python3.9/site-packages/yahoo_fin/stock_info.py", line 197, in get_quote_table
    price_etc = [elt for elt in tables if elt.iloc[0][0] == "Previous Close"][0]
IndexError: list index out of range

https://finance.yahoo.com/quote/CL=F?p=CL=F

**Comment by atreadw1492** [comment]
Thanks for pointing this out.  The next release corrects for this issue (due out in the next couple weeks).
