### ISSUE TITLE
error with get_quote_table  for tickers ( e.g. AMTD )

### ISSUE THREAD

**Issue by bekandze** [atreadw1492/yahoo_fin#33]
si.get_quote_table('MYL')

/usr/local/lib/python3.6/dist-packages/yahoo_fin/stock_info.py in get_quote_table(ticker, dict_result)
    293     tables = pd.read_html(site)
    294 
    295     data = tables[0].append(tables[1])
    296 
    297     data.columns = ["attribute" , "value"]

IndexError: list index out of range

**Comment by atreadw1492** [comment]
AMTD is no longer actively traded since it was bought out by Charles Schwab - that's why it won't work with si.get_quote_table.  MYL is also not a valid ticker, but MYL.VI is, which should work with si.get_quote_table
