### ISSUE TITLE
Error while calling get_earnings(ticker)

### ISSUE THREAD

**Issue by guileluk** [atreadw1492/yahoo_fin#35]
File "C:\Users\Acer\Desktop\Ray\test\venv\lib\site-packages\yahoo_fin\stock_info.py", line 765, in get_earnings
    result["quarterly_results"] = pd.DataFrame.from_dict(temp["earningsChart"]["quarterly"])
TypeError: 'NoneType' object is not subscriptable

**Comment by guileluk** [comment]
e.g. get_earnings('2800.HK')

**Comment by atreadw1492** [comment]
Some tickers may not have earnings information freely available, like 2800.HK (see https://finance.yahoo.com/quote/2800.HK/financials?p=2800.HK for example).  That's what's causing the issue.
