### ISSUE TITLE
Get company info

### ISSUE THREAD

**Issue by shahab-cl** [atreadw1492/yahoo_fin#43]
I am looking for a way to get sector info as well as details about the company.  Is there a way to get the profile page.  e.g. https://finance.yahoo.com/quote/AAPL/profile?p=AAPL

**Comment by chikin1993** [comment]
Hi, I've created two functions for this and made a pull request!

**Comment by atreadw1492** [comment]
Thanks, @chikin1993.  These are included in the latest version on PyPI, @shahab-cl

**Comment by KrishPraba** [comment]
### Yahoo-Fin get_company_info not working

I am receiving the following error when I try to access the get_company_info() function. Why is this occurring?

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-5-349248345884>](https://localhost:8080/#) in <cell line: 3>()
      1 from yahoo_fin.stock_info import get_company_officers
      2 
----> 3 get_company_officers("aapl")

[/usr/local/lib/python3.10/dist-packages/yahoo_fin/stock_info.py](https://localhost:8080/#) in get_company_officers(ticker)
   1029     site = f"[https://finance.yahoo.com/quote/{ticker}/profile?p={ticker}](https://finance.yahoo.com/quote/%7Bticker%7D/profile?p={ticker})"
   1030     json_info = _parse_json(site)
-> 1031     json_info = json_info["assetProfile"]["companyOfficers"]
   1032     info_frame = pd.DataFrame.from_dict(json_info)
   1033     info_frame = info_frame.set_index("name")

TypeError: string indices must be integers
```

**Comment by cporrasn** [comment]
Hello! I am getting the same error. Is it possible to solve it?

**Comment by hlvas** [comment]
yes same here! ... is this broken or something?

**Comment by oevl** [comment]
Seems it is still broken.
