### ISSUE TITLE
get_earnings_history - data discrepancies

### ISSUE THREAD

**Issue by msingh00** [atreadw1492/yahoo_fin#46]
I am not sure if this is an issue with code or simply quality of data source.   I am pulling historical earnings for AAPL using the get_earnings_history function and noticed a couple of data issues:

1. There doesn't seem to be an earnings date or eps for Q2 of 2001
2. for 2003-04-16, both estimate and actual are shown as 0.0 and suprise is 100%

I am guessing it may be an issue at the source - maybe needs some cleaning.

**Comment by atreadw1492** [comment]
@msingh00 I believe this is an issue at the source, unfortunately, but if anything changes, I'll make an update.
