### ISSUE TITLE
Gainer/Loser Volume

### ISSUE THREAD

**Issue by jpslabaugh** [atreadw1492/yahoo_fin#5]
Is the volume off for anyone else when retrieving gainers or losers?

>>> yahoo_gainers
    Symbol                                   Name  Price (Intraday)  ...  Avg Vol (3 month)    Market Cap  PE Ratio (TTM)
0     AMKR                 Amkor Technology, Inc.           14.6700  ...       8.646730e+14  3.517000e+09           70.20

>>> yahoo_gainers['Volume'][0]
3618000.0
>>> yahoo_gainers['Avg Vol (3 month)'][0]
864673000000000.0

Here's the actual volume:
>>> yahoo.get_quote_table('AMKR')
{'1y Target Est': 7.73, '52 Week Range': '5.74 - 14.81', 'Ask': '14.66 x 1400', 'Avg. Volume': 864673.0, 'Beta (3Y Monthly)': 1.66, 'Bid': '14.63 x 1100', "Day's Range": '13.15 - 14.81', 'EPS (TTM)': 0.21, 'Earnings Date': 'Oct 28, 2019', 'Ex-Dividend Date': nan, 'Forward Dividend & Yield': 'N/A (N/A)', 'Market Cap': '3.502B', 'Open': 13.46, 'PE Ratio (TTM)': 69.9, 'Previous Close': 11.08, 'Quote Price': 14.614999771118164, 'Volume': 3980124.0}

**Comment by atreadw1492** [comment]
This will be corrected in the next release - due out in the next 2 weeks.  It's because of an issue converting the strings that Yahoo Finance uses to represent the volume (e.g. "20.3M" instead of 20,300,000).
