### ISSUE TITLE
get_live_price() Not working

### ISSUE THREAD

**Issue by hebawom** [atreadw1492/yahoo_fin#59]
This function was working until 7pm GMT. But now it gives me this Traceback:

<img width="1026" alt="Screenshot 2021-07-09 at 19 00 11" src="https://user-images.githubusercontent.com/33041980/125119198-a928f400-e0e8-11eb-916c-1454b68478e7.png">

I'm using the latest package version: 0.8.9.

Is this related to the yahoo site change? This was using 'AAPL'

**Comment by jaydevshelat** [comment]
+1  Suddenly stopped working in last 12-18 hours.

**Comment by hebawom** [comment]
Just to confirm - the pending PR does not fix this issue

**Comment by hebawom** [comment]
Printing out the response to the yahoo request:
<Response [403]>
Not sure that is fixable - right?

**Comment by erickmartinez** [comment]
It happened the same to me. I looked at the code in the `get_data` function. If you add the user-agent to the header:

```
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}
result = requests.get(site, params=params, headers=headers)

```
 and pass it to the request, it does work. However, I don't know if yahoo will eventually block these requests.

**Comment by atreadw1492** [comment]
Thanks for notifying me of the issue - I'm looking into it, and will try to push a patch (if possible) within the next 24 hours

**Comment by atreadw1492** [comment]
Please download the latest version - 0.8.9.1.  I just pushed this patch to PyPI to update the headers, per @erickmartinez suggestion.  This should hopefully resolve these issues.  Thank you all for posting and the suggestions.
