### ISSUE TITLE
Expected object or value

### ISSUE THREAD

**Issue by samarthsarin** [atreadw1492/yahoo_fin#6]
Unable to run any stock price retrieval from the website.

**Comment by ofeksr** [comment]
same here :(

```
df = get_data(ticker, end_date = pd.Timestamp.today() + pd.DateOffset(10))
temp = loads(needed)
ValueError: Expected object or value
```

**Comment by kefa8** [comment]
Changed the below lines in stock_info.py:

    start = html.index('"HistoricalPriceStore"')
    # end = html.index("firstTradeDate")
    end = html.index("}]}", start)

    needed = html[start:(end+3)]
    needed = needed.strip('"HistoricalPriceStore":')
    # needed = needed.strip(""","isPending":false,'""")
    # needed = needed + "}"

**Comment by tiagolvsantos** [comment]
Any update on a version fix of these?

**Comment by atreadw1492** [comment]
This should be fixed by reinstalling with the latest version.  I wrote a few details on the updates here: http://theautomatic.net/2019/12/16/updates-to-yahoo_fin-package/
