### ISSUE TITLE
Historicla data is missing, while the data is available in yahoo website

### ISSUE THREAD

**Issue by ywluohao** [atreadw1492/yahoo_fin#67]
Hi, when i was trying to use get_data(), the result is quite inconsistent. It works for some tickers, but not for all tickers.
For Example, if I run
`from yahoo_fin.stock_info import get_data`
`get_data("PYPL")`

<img width="834" alt="Screen Shot 2021-08-04 at 10 00 19 AM" src="https://user-images.githubusercontent.com/41532093/128194313-419def31-6884-4a32-a4a1-2fa3f17b14ef.png">

But probably 10 minutes later, maybe "PYPL" works, but some other tickers will fail. 

I am not sure is this issue temporary or permanent.

**Comment by ywluohao** [comment]
it looks yahoo blocked my ip. If i use VPN, all the data is available.

**Comment by kaizenlabs** [comment]
They blocked mine too. Why you no let me rape your API, Yahoo? LOL
