### ISSUE TITLE
FEATURE: Is the market open or closed?

### ISSUE THREAD

**Issue by IsakNyberg** [atreadw1492/yahoo_fin#7]
Perhaps a function similar to: 
get_market_status()
That would return wheter the market is open, closed, after hours, or premarket.

**Comment by atreadw1492** [comment]
Thanks for the suggestion!  I'll add this to the possibilities for a future release.  

> 
> 
> Perhaps a function similar to:
> get_market_status()
> That would return wheter the market is open, closed, after hours, or premarket.
