### ISSUE TITLE
si.get_stats not working

### ISSUE THREAD

**Issue by DetlefSchmitt** [atreadw1492/yahoo_fin#72]
Hi, 
the below script used to work for me just fine. But now it doesn't any longer.
I minimized the script to locate the problem. It seems "si.get_stats" causes the problem.
Please have a look at it.

`import pandas as pd
from yahoo_fin import stock_info as si

ti = pd.read_csv('/Users/detlefschmitt/Documents/Excel files/Clinical trial analysis/Python/Tickers/TickerList.csv')
ti2 = ti["Ticker"].tolist()

stock_list = ti2

stats = {}

for ticker in stock_list:
  data = si.get_stats(ticker)
  stats[ticker] = data

combined = pd.concat(stats)
combined = combined.reset_index()
del combined["level_1"]
combined.columns = ["Ticker", "Attribute", "Recent"]

df = pd.DataFrame(combined)
df2 = df.pivot(index='Ticker', columns='Attribute', values='Recent')

cols = [3,7,12,13,14,17,18,19,20,22,23,24,25,26,27,28,30,31,32,33,34,35,38,39,41,43,45,49,51,56,57,58]
df2.drop(df2.columns[cols],axis=1,inplace=True)

df2.rename(columns={ df2.columns[0]: "% Insider" }, inplace = True)
df2.rename(columns={ df2.columns[1]: "% Institution" }, inplace = True)
df2.rename(columns={ df2.columns[2]: "200-Day MA" }, inplace = True)
df2.rename(columns={ df2.columns[3]: "50-Day MA" }, inplace = True)
df2.rename(columns={ df2.columns[4]: "52-Week H" }, inplace = True)
df2.rename(columns={ df2.columns[5]: "52-Week L" }, inplace = True)
df2.rename(columns={ df2.columns[6]: "Avg Vol 10D" }, inplace = True)
df2.rename(columns={ df2.columns[7]: "Avg Vol 3M" }, inplace = True)
df2.rename(columns={ df2.columns[8]: "Beta" }, inplace = True)
df2.rename(columns={ df2.columns[9]: "Book/Share" }, inplace = True)
df2.rename(columns={ df2.columns[10]: "EBITDA" }, inplace = True)
df2.rename(columns={ df2.columns[11]: "Enterprice V" }, inplace = True)
df2.rename(columns={ df2.columns[12]: "Float" }, inplace = True)
df2.rename(columns={ df2.columns[13]: "Market Cap" }, inplace = True)
df2.rename(columns={ df2.columns[14]: "Price/Book" }, inplace = True)
df2.rename(columns={ df2.columns[15]: "Price/Sales" }, inplace = True)
df2.rename(columns={ df2.columns[16]: "Q Rev (YOY)" }, inplace = True)
df2.rename(columns={ df2.columns[17]: "Return on Equity" }, inplace = True)
df2.rename(columns={ df2.columns[18]: "Revenue/Share" }, inplace = True)
df2.rename(columns={ df2.columns[19]: "Shares" }, inplace = True)
df2.rename(columns={ df2.columns[20]: "Shares Short" }, inplace = True)
df2.rename(columns={ df2.columns[21]: "Short prior" }, inplace = True)
df2.rename(columns={ df2.columns[22]: "% Short" }, inplace = True)
df2.rename(columns={ df2.columns[23]: "Cash" }, inplace = True)
df2.rename(columns={ df2.columns[24]: "Cash/Share" }, inplace = True)
df2.rename(columns={ df2.columns[25]: "Debt" }, inplace = True)
df2.rename(columns={ df2.columns[26]: "Debt/Equity" }, inplace = True)

order = [13,11,15,14,8,4,5,3,2,7,6,19,12,0,1,20,22,21,17,18,16,10,23,24,25,26,9]
df3 = df2[[df2.columns[i] for i in order]]

df3.to_csv(r'/Users/detlefschmitt/Documents/Excel files/Clinical trial analysis/Python/Output Data/stats.csv')`

**Comment by DetlefSchmitt** [comment]
Here is the minimum script causing the same error as the script above.

`import pandas as pd
from yahoo_fin import stock_info as si

data = si.get_stats("aapl")`

**Comment by atreadw1492** [comment]
@DetlefSchmitt, are you using the most recent version - 0.8.9.1?

**Comment by DetlefSchmitt** [comment]
@atreadw1492 I will check. I am away from my computer for a few days. I will get back to you after I have checked.

**Comment by DetlefSchmitt** [comment]
@atreadw1492 updating solved the problem. Thanks. One other issue. The stats file used to contain 59 columns. However, the file I received today only contains 51 columns. Some important values are missing including Enterprise Value, Market Cap, Price/Book, Price/Sales. Why is that?

**Comment by DetlefSchmitt** [comment]
&atreadw1482 I found that with "get_stats_valuation" one can get the 9 stats that are no longer included in "get_stats". Now I just have to figure out how to combine the data.

**Comment by atreadw1492** [comment]
@DetlefSchmitt Great, glad that worked for you!  And, it has to do with Yahoo Finance's API, it's easier on the backend to separate pulling those data points in two separate functions.  The previous implementation was less stable to changes in Yahoo Finance.
